version: '3.7'
services:
  redis:
    image: redis:alpine
    command: redis-server --port 6380
    container_name: redis_boot
    hostname: redis_boot
    labels:
      - "name=redis"
      - "mode=standalone"
    ports:
      - 6380:6380