---
spring:
  config:
    activate:
      on-profile: local
  redis:
    port: 6380
    host: localhost
  datasource:
    hikari:
      jdbc-url: jdbc:mysql://localhost:3306/coupon?useUnicode=yes&characterEncoding=UTF-8&rewriteBatchedStatements=true
      driver-class-name: com.mysql.cj.jdbc.Driver
      maximum-pool-size: 50
      max-lifetime: 30000
      username: jerry
      password: 1234
  jpa:
    hibernate:
      ddl-auto: none
logging:
  level:
    sql:
      debug

---
spring:
  config:
    activate:
      on-profile: test
  redis:
    port: 6380
    host: localhost
  datasource:
    hikari:
      jdbc-url: jdbc:mysql://localhost:3306/coupon?useUnicode=yes&characterEncoding=UTF-8&rewriteBatchedStatements=true
      driver-class-name: com.mysql.cj.jdbc.Driver
      maximum-pool-size: 50
      max-lifetime: 30000
      username: jerry
      password: 1234
  jpa:
    hibernate:
      ddl-auto: none
logging:
  level:
    sql:
      debug

---
spring:
  config:
    activate:
      on-profile: prod
  redis:
    port: 6380
    host: JERRY_REDIS_HOST
  datasource:
    hikari:
      jdbc-url: JERRY_MYSQL_URL
      driver-class-name: com.mysql.cj.jdbc.Driver
      maximum-pool-size: 50
      max-lifetime: 30000
      username: JERRY_MYSQL_URL_USER
      password: JERRY_MYSQL_URL_PASSWORD